import type { Metadata } from 'next'
import { createMetadata } from '@/lib/metadata'
import { FadeUp } from '@/components/ui/FadeUp'
import { SectionLabel } from '@/components/ui/SectionLabel'

export const metadata: Metadata = createMetadata({
  title: 'Privacy Policy',
  description:
    'How Forte AI Solutions collects, uses, and protects your personal information.',
  path: '/privacy',
})

export default function PrivacyPage() {
  return (
    <>
      <section className="relative bg-navy pt-32 pb-20 md:pt-44 md:pb-28 overflow-hidden">
        <div className="relative mx-auto max-w-4xl px-6">
          <FadeUp>
            <SectionLabel label="Legal" />
          </FadeUp>
          <FadeUp delay={0.1}>
            <h1 className="mt-6 font-display text-4xl font-normal leading-display text-white md:text-5xl">
              Privacy Policy
            </h1>
          </FadeUp>
          <FadeUp delay={0.2}>
            <p className="mt-4 font-body text-sm font-light text-white/40">
              Last updated: March 2026
            </p>
          </FadeUp>
        </div>
      </section>

      <section className="bg-navy-deep py-20 md:py-28">
        <div className="mx-auto max-w-4xl px-6">
          <div className="space-y-12">
            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  Overview
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  Forte AI Solutions (&quot;Forte,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) respects your
                  privacy and is committed to protecting the personal information you
                  share with us. This Privacy Policy explains what information we
                  collect, how we use it, and your rights regarding that information
                  when you visit forteaisolutions.com (the &quot;Site&quot;).
                </p>
              </div>
            </FadeUp>

            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  Information We Collect
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  We collect information in the following ways:
                </p>
                <h3 className="font-display text-lg font-normal text-white/80 pt-2">
                  Contact Form
                </h3>
                <p className="font-body text-base font-light leading-body text-white/60">
                  When you submit our contact form, we collect your full name,
                  company name, job title, work email address, and the message you
                  provide describing your data challenge. This information is sent
                  to our team via email for the purpose of responding to your inquiry.
                </p>
                <h3 className="font-display text-lg font-normal text-white/80 pt-2">
                  AI Chatbot
                </h3>
                <p className="font-body text-base font-light leading-body text-white/60">
                  Our website includes an AI-powered chatbot to help answer questions
                  about our services. Messages you send to the chatbot are processed
                  by a third-party AI provider (Anthropic) to generate responses.
                  Please note that chatbot responses are generated by artificial
                  intelligence and may occasionally be inaccurate or incomplete. They
                  are provided for informational purposes only and do not constitute
                  professional advice or a binding offer.
                </p>
                <p className="font-body text-base font-light leading-body text-white/60">
                  If you choose to share your name and email through the chatbot, that
                  information along with a summary of your conversation may be sent
                  to our team to follow up on your inquiry. Chat conversations are
                  not stored in a persistent database and are only retained in the
                  email notification sent to our team.
                </p>
                <h3 className="font-display text-lg font-normal text-white/80 pt-2">
                  Automated Assessment
                </h3>
                <p className="font-body text-base font-light leading-body text-white/60">
                  During chatbot interactions, our system may automatically assess
                  general organizational fit based on the content of your
                  conversation. This may include an evaluation of factors such as
                  organization size, data maturity, and service alignment. This
                  assessment is used solely for internal purposes to help our team
                  better understand your needs and prepare for potential follow-up
                  conversations. It is not shared with third parties and is not used
                  to make any automated decisions that produce legal or similarly
                  significant effects.
                </p>
                <h3 className="font-display text-lg font-normal text-white/80 pt-2">
                  Analytics
                </h3>
                <p className="font-body text-base font-light leading-body text-white/60">
                  We use Google Analytics and Vercel Analytics to understand how
                  visitors interact with our Site. These services may collect
                  information such as your IP address, browser type, operating
                  system, referring URLs, pages visited, and time spent on the Site.
                  This data is collected using cookies and similar technologies.
                  Google Analytics data is subject to Google&apos;s privacy policy.
                </p>
              </div>
            </FadeUp>

            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  How We Use Your Information
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  We use the information we collect to respond to your inquiries
                  and provide information about our services, to improve our website
                  and understand how visitors use it, to assess organizational fit
                  and prepare for follow-up conversations, to protect against spam
                  and abuse through rate limiting and bot detection, and to
                  communicate with you if you have requested follow-up. We do not
                  sell, rent, or trade your personal information to third parties.
                </p>
              </div>
            </FadeUp>

            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  Data Retention
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  Contact form submissions and chatbot lead notifications are
                  retained in our email systems for as long as necessary to respond
                  to your inquiry and maintain a record of our communications. We
                  do not store chat conversations in a persistent database. Analytics
                  data is retained according to the default retention periods of
                  Google Analytics and Vercel Analytics. You may request deletion
                  of your personal information at any time by contacting us at
                  hello@forteaisolutions.com, and we will process your request
                  within 30 days.
                </p>
              </div>
            </FadeUp>

            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  Third-Party Services
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  We use the following third-party services to operate the Site:
                  Anthropic (AI chatbot processing), Resend (email delivery for
                  form submissions and lead notifications), Google Analytics
                  (website analytics), Vercel (website hosting and analytics),
                  and Upstash (rate limiting). Each of these services has its own
                  privacy policy governing how they handle data. These services
                  may process your data on servers located in the United States
                  or other jurisdictions. By using the Site, you acknowledge that
                  your information may be transferred to and processed in these
                  locations.
                </p>
              </div>
            </FadeUp>

            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  Cookies and Consent
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  Our Site uses cookies and similar tracking technologies. When
                  you first visit the Site, you will be presented with a cookie
                  consent banner allowing you to accept or decline non-essential
                  cookies. If you decline, analytics tracking (including Google
                  Analytics) will be disabled for your session. Essential cookies
                  required for basic site functionality may still be used. You
                  can also control cookies through your browser settings at any
                  time. Disabling cookies may affect your experience on the Site
                  but will not prevent you from accessing our content.
                </p>
              </div>
            </FadeUp>

            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  Data Security
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  We take reasonable measures to protect your information. Our Site
                  enforces HTTPS encryption, includes security headers to prevent
                  common web vulnerabilities, and restricts access to device features
                  such as camera, microphone, and geolocation. However, no method of
                  electronic transmission or storage is completely secure, and we
                  cannot guarantee absolute security.
                </p>
              </div>
            </FadeUp>

            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  Your Rights
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  Depending on your location, you may have rights under applicable
                  privacy laws, including the California Consumer Privacy Act
                  (CCPA/CPRA), the Virginia Consumer Data Protection Act (VCDPA),
                  the Colorado Privacy Act, and similar state laws. These rights
                  may include the right to know what personal information we
                  collect and how it is used, the right to request deletion of your
                  personal information, the right to correct inaccurate personal
                  information, the right to opt out of the sale or sharing of
                  personal information (note: we do not sell or share personal
                  information for cross-context behavioral advertising), and the
                  right to not be discriminated against for exercising your privacy
                  rights. To exercise any of these rights, please contact us at
                  hello@forteaisolutions.com. We will respond to verifiable requests
                  within the timeframes required by applicable law.
                </p>
              </div>
            </FadeUp>

            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  Children&apos;s Privacy
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  The Site is not directed at children under the age of 13, and we
                  do not knowingly collect personal information from children under
                  13. If we become aware that we have collected personal information
                  from a child under 13, we will take steps to delete that
                  information promptly. If you believe a child under 13 has provided
                  us with personal information, please contact us at
                  hello@forteaisolutions.com.
                </p>
              </div>
            </FadeUp>

            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  Changes to This Policy
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  We may update this Privacy Policy from time to time. Any changes
                  will be posted on this page with an updated &quot;Last updated&quot; date.
                  We encourage you to review this page periodically.
                </p>
              </div>
            </FadeUp>

            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  Contact Us
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  If you have questions about this Privacy Policy or how we handle
                  your information, please contact us at hello@forteaisolutions.com.
                </p>
              </div>
            </FadeUp>
          </div>
        </div>
      </section>
    </>
  )
}
