import type { Metadata } from 'next'
import { createMetadata } from '@/lib/metadata'
import { FadeUp } from '@/components/ui/FadeUp'
import { SectionLabel } from '@/components/ui/SectionLabel'

export const metadata: Metadata = createMetadata({
  title: 'Terms of Service',
  description:
    'Terms and conditions for using the Forte AI Solutions website.',
  path: '/terms',
})

export default function TermsPage() {
  return (
    <>
      <section className="relative bg-navy pt-32 pb-20 md:pt-44 md:pb-28 overflow-hidden">
        <div className="relative mx-auto max-w-4xl px-6">
          <FadeUp>
            <SectionLabel label="Legal" />
          </FadeUp>
          <FadeUp delay={0.1}>
            <h1 className="mt-6 font-display text-4xl font-normal leading-display text-white md:text-5xl">
              Terms of Service
            </h1>
          </FadeUp>
          <FadeUp delay={0.2}>
            <p className="mt-4 font-body text-sm font-light text-white/40">
              Last updated: March 2026
            </p>
          </FadeUp>
        </div>
      </section>

      <section className="bg-navy-deep py-20 md:py-28">
        <div className="mx-auto max-w-4xl px-6">
          <div className="space-y-12">
            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  Agreement to Terms
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  By accessing or using forteaisolutions.com (the &quot;Site&quot;), you
                  agree to be bound by these Terms of Service (&quot;Terms&quot;). If you
                  do not agree to these Terms, please do not use the Site. Forte
                  AI Solutions (&quot;Forte,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) reserves the right
                  to update these Terms at any time. Changes will be posted on
                  this page with an updated date. Continued use of the Site after
                  changes are posted constitutes acceptance of the updated Terms.
                </p>
              </div>
            </FadeUp>

            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  Use of the Site
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  The Site is provided for informational purposes and to facilitate
                  communication about our consulting services. You agree to use the
                  Site only for lawful purposes and in a manner that does not
                  infringe on the rights of others or restrict their use of the
                  Site. You may not use the Site to transmit harmful, abusive, or
                  unauthorized content, or to attempt to gain unauthorized access
                  to any part of the Site or its systems.
                </p>
              </div>
            </FadeUp>

            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  AI Chatbot
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  Our Site includes an AI-powered chatbot designed to answer
                  general questions about Forte AI Solutions and our services.
                  Responses generated by the chatbot are produced by artificial
                  intelligence and are for informational purposes only. They do
                  not constitute professional advice, a binding offer, a guarantee
                  of results, or a contractual commitment. The chatbot may
                  occasionally produce inaccurate or incomplete information. You
                  should not rely solely on chatbot responses for business
                  decisions. For specific guidance, please contact us directly.
                </p>
              </div>
            </FadeUp>

            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  Intellectual Property
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  All content on the Site, including text, graphics, logos,
                  images, and software, is the property of Forte AI Solutions or
                  its content suppliers and is protected by applicable intellectual
                  property laws. You may not reproduce, distribute, modify, or
                  create derivative works from any content on the Site without
                  our prior written consent.
                </p>
              </div>
            </FadeUp>

            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  Services Disclaimer
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  Information on the Site about our services, including
                  descriptions, timelines, and deliverables, is provided for
                  general informational purposes. Actual engagements are governed
                  by separate service agreements. Nothing on the Site constitutes
                  a binding contract, guarantee of specific outcomes, or promise
                  of results. Every organization is different, and outcomes depend
                  on factors specific to your environment, data, and team.
                </p>
              </div>
            </FadeUp>

            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  Limitation of Liability
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  The Site and its content are provided &quot;as is&quot; and &quot;as available&quot;
                  without warranties of any kind, either express or implied,
                  including but not limited to implied warranties of
                  merchantability, fitness for a particular purpose, and
                  non-infringement. Forte AI Solutions does not warrant that the
                  Site will be uninterrupted, error-free, or free of harmful
                  components. To the fullest extent permitted by law, Forte AI
                  Solutions shall not be liable for any indirect, incidental,
                  special, consequential, or punitive damages arising from your
                  use of or inability to use the Site, including but not limited
                  to loss of data, loss of profits, or business interruption,
                  regardless of the theory of liability.
                </p>
              </div>
            </FadeUp>

            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  Indemnification
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  You agree to indemnify, defend, and hold harmless Forte AI
                  Solutions, its founder, employees, agents, and affiliates from
                  and against any claims, liabilities, damages, losses, costs, or
                  expenses (including reasonable attorney&apos;s fees) arising out of
                  or related to your use of the Site, your violation of these
                  Terms, or your violation of any rights of a third party.
                </p>
              </div>
            </FadeUp>

            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  Third-Party Links
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  The Site may contain links to third-party websites or services
                  that are not owned or controlled by Forte AI Solutions. We are
                  not responsible for the content, privacy policies, or practices
                  of any third-party sites. We encourage you to review the terms
                  and privacy policies of any third-party sites you visit.
                </p>
              </div>
            </FadeUp>

            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  Governing Law and Dispute Resolution
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  These Terms shall be governed by and construed in accordance
                  with the laws of the State of Florida, without regard to its
                  conflict of law provisions. Any dispute arising from or relating
                  to these Terms or your use of the Site shall be resolved
                  exclusively in the state or federal courts located in the
                  State of Florida. You consent to the personal jurisdiction and
                  venue of such courts. Before initiating formal legal proceedings,
                  you agree to first attempt to resolve any dispute informally by
                  contacting us at hello@forteaisolutions.com.
                </p>
              </div>
            </FadeUp>

            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  Severability
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  If any provision of these Terms is found to be unenforceable or
                  invalid by a court of competent jurisdiction, that provision
                  shall be limited or eliminated to the minimum extent necessary,
                  and the remaining provisions of these Terms shall remain in full
                  force and effect.
                </p>
              </div>
            </FadeUp>

            <FadeUp>
              <div className="space-y-4">
                <h2 className="font-display text-2xl font-normal text-white">
                  Contact Us
                </h2>
                <p className="font-body text-base font-light leading-body text-white/60">
                  If you have questions about these Terms, please contact us at
                  hello@forteaisolutions.com.
                </p>
              </div>
            </FadeUp>
          </div>
        </div>
      </section>
    </>
  )
}
